name: baby_vaccination

description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

  dartz: ^0.10.1
  connectivity_plus: ^6.1.4

  flutter_svg: ^2.1.0
  cached_network_image: ^3.4.1

  flutter_secure_storage: ^9.2.4

  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  android_id: ^0.4.0

  curved_navigation_bar: ^1.0.6

  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  get_it: ^8.0.3
  injectable: ^2.7.1+4
  freezed_annotation: ^3.1.0
  json_annotation: ^4.11.0
  go_router: ^17.1.0

  smooth_page_indicator: ^1.1.0

  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  google_sign_in: ^6.2.1
  path_provider: ^2.1.5
  open_file: ^3.3.2
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.0.0
  rive: ^0.14.4
  flutter_screenutil: ^5.9.3
  firebase_messaging: ^16.0.0
  flare_flutter: ^3.0.2
  flare_splash_screen: ^4.0.0
  # flutter_local_notifications: ^21.0.0
  google_maps_flutter: ^2.17.0
  google_maps_polyline: ^1.0.3
  flutter_polyline_points: ^3.1.0
  location: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.12
  injectable_generator: ^2.7.1+4
  freezed: ^3.2.5
  json_serializable: ^6.13.1
  flutter_gen_runner: ^5.13.0+1
  flutter_lints: ^6.0.0

dependency_overrides:
  platform: ^3.1.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/flare/
    - assets/images/
    - assets/icons/
    - assets/rive/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

    - family: Beiruti
      fonts:
        - asset: assets/fonts/Beiruti-Light.ttf
          weight: 300
        - asset: assets/fonts/Beiruti-Regular.ttf
          weight: 400
        - asset: assets/fonts/Beiruti-Medium.ttf
          weight: 500
        - asset: assets/fonts/Beiruti-Bold.ttf
          weight: 700

flutter_intl:
  enabled: true
  arb_dir: lib/core/localization/intl
  output_dir: lib/core/localization/intl

flutter_gen:
  output: lib/core/gen/
  line_length: 80
  
  integrations:
    flutter_svg: true
    lottie: true
  
  assets:
    outputs:
      package_parameter_enabled: false
      directory_path_enabled: true
  
  parse_metadata: true
